image: microsoft/dotnet:latest

stages:
    - docker

image: gitlab/dind
    
variables:
    test: "Algoritmos.Tests"
    buildConfiguration: 'Release'


docker:
    stage: docker
    script: 
        - "docker build -f Dockerfile -t $dockerId/$imageName ."
        - "docker login -u $dockerId -p $pswd"
        - "docker push $dockerId/$imageName"
    