image: microsoft/dotnet:latest

stages:
    - build
    - test
    - docker

variables:
    test: "Algoritmos.Tests"
    buildConfiguration: 'Release'

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "dotnet test"  

docker:
    stage: docker
    script: 
        - "docker build -f Dockerfile -t $dockerId/$imageName ."
        - "docker login -u $dockerId -p $pswd"
        - "docker push $dockerId/$imageName"
    